### ISSUE TITLE
Add Github Add to Project action

### ISSUE THREAD

**Issue by robbertbos** [MinBZK/ai-validation#175]
### Description: 
If there are issues (not PR's) made by other parties, we want to have them as actions in our project.
https://github.com/actions/add-to-project

### Technical Steps: 
- Make new GitHub action for all projects (+/- 10 projects)

**Comment by uittenbroekrobbert** [comment]
The action used for this always refers to a PAT (Personal Access Token). However, this does not seem useful to me at all, because we then link it to a person. Perhaps this can also/better be done with a token at the organization level. There is already another ticket for that, to investigate that, I suggest we wait for that. Issue https://github.com/orgs/MinBZK/projects/7/views/9?pane=issue&itemId=67791563

**Comment by berrydenhartog** [comment]
added project github workflow to all 10 non archived projects from https://github.com/orgs/MinBZK/teams/ai-validation-team/repositories

**Comment by berrydenhartog** [comment]
stored pat in vault. it is valid for 1 year
